#!/bin/bash
# Run an embarrassingly parallel job, where each command is totally independent
# Uses GNU Parallel as a task scheduler, then executes each task on the available CPUs with pbsdsh

#PBS -q normalbw
#PBS -l ncpus=20
#PBS -l walltime=15:00:00
#PBS -l mem=200gb
#PBS -l wd
#PBS -P v46
#PBS -l jobfs=200GB
#PBS -l storage=scratch/v46+gdata/v46+gdata/ux62+gdata/xp65+gdata/su28
#PBS -N create_dqdt_doyclim
#PBS -o /home/563/fm6730/localrepo/wave_vertical_heating/scripts/logs/create_dqdt_doyclim.out
#PBS -e /home/563/fm6730/localrepo/wave_vertical_heating/scripts/logs/create_dqdt_doyclim.err

module use /g/data/xp65/public/modules/
module load conda/analysis3

# var=t
python3 /home/563/fm6730/localrepo/wave_vertical_heating/scripts/main/create_dqdt_doyclim.py 