#!/bin/bash
#PBS -P v46
#PBS -q normalbw
#PBS -l walltime=10:00:00
#PBS -l ncpus=20
#PBS -l mem=200GB
#PBS -N q1_wave_filter
#PBS -o /home/563/fm6730/localrepo/wave_vertical_heating/scripts/logs/q1_wave_filter.out
#PBS -e /home/563/fm6730/localrepo/wave_vertical_heating/scripts/logs/q1_wave_filter.err
#PBS -l jobfs=200GB
#PBS -l wd
#PBS -l storage=scratch/v46+gdata/v46+gdata/ux62+gdata/xp65+gdata/su28

# Expects ens, wave, var to be passed in via:
#   qsub -v ens="e01",wave="mjo",var="q1" filter_wave_s2s.qsub
# Loops through every month in dates.txt sequentially, calling ncl once
# per (day_min0, day_min1, day_min2) for this ens/wave/var combination.

module use /g/data/xp65/public/modules/
module load ncl 
module load parallel

# DATELIST="/home/563/fm6730/localrepo/wave_vertical_heating/scripts/input_forjob/dates_s2sfilter.txt"
DATELIST="/home/563/fm6730/localrepo/wave_vertical_heating/scripts/input_forjob/dates_s2sfilter_patch.txt"
SCRIPT="/home/563/fm6730/localrepo/wave_vertical_heating/scripts/main/ncl_filter_wave_s2s.ncl"

JOB_CPU=5

echo "ens    = [$ens]"
echo "wave   = [$wave]"
echo "var    = [$var]"
echo "SCRIPT = [$SCRIPT]"

JOB_CPU=5

run_case () {
    day_min0="$1"
    day_min1="$2"
    day_min2="$3"

    echo "=============================="
    echo "ens     = [$ens]"
    echo "wave    = [$wave]"
    echo "var     = [$var]"
    echo "day_min0 = [$day_min0]"
    echo "day_min1 = [$day_min1]"
    echo "day_min2 = [$day_min2]"
    echo "SCRIPT   = [$SCRIPT]"
    echo "=============================="


    module use /g/data/xp65/public/modules/
    module load conda/analysis3
    module load ncl
    module load parallel

    ncl "ens=\"$ens\"" \
        "wave=\"$wave\"" \
        "var=\"$var\"" \
        "day_min0=\"$day_min0\"" \
        "day_min1=\"$day_min1\"" \
        "day_min2=\"$day_min2\"" \
        "$SCRIPT" || return 1
}

export -f run_case
export ens wave var SCRIPT

parallel -j "$JOB_CPU" --colsep ' ' \
    run_case {1} {2} {3} :::: "$DATELIST"
